# Generated by Django 2.2 on 2021-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2016)),
                ('Major', models.IntegerField()),
                ('Minor', models.IntegerField()),
                ('BldgNbr', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('main_use', models.CharField(max_length=20)),
                ('Number_of_Stories', models.IntegerField(default=1)),
                ('Construction_Class', models.IntegerField()),
                ('Year_built', models.IntegerField()),
                ('Year_remodeled', models.IntegerField()),
                ('Building_Name', models.CharField(max_length=200)),
                ('Cook_type', models.CharField(max_length=200)),
                ('Space_heat_type', models.CharField(max_length=200)),
                ('DHW_type', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('Leg_District', models.IntegerField()),
                ('Floor_Area', models.IntegerField()),
                ('Description', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=500)),
                ('Architect', models.CharField(max_length=200)),
                ('Engineer', models.CharField(max_length=200)),
                ('Builder', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=47.6)),
                ('lon', models.FloatField(default=-122.3)),
            ],
        ),
    ]
