# Generated by Django 2.2 on 2021-12-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Construction_Class',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Floor_Area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Year_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Year_remodeled',
            field=models.IntegerField(null=True),
        ),
    ]
