# Generated by Django 2.2 on 2021-12-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBmap', '0002_auto_20211211_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='BldgNbr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Major',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Minor',
            field=models.IntegerField(null=True),
        ),
    ]
