# Generated by Django 2.2 on 2021-12-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBmap', '0003_auto_20211221_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='img_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
